#!/bin/bash
set -e

PROJECT_PATH=$(dirname "$(dirname $0)")

VERSION=1.1
ICON_PATH="$PROJECT_PATH/images/fox.ico"
OUT_PATH="$PROJECT_PATH/bin"

rm -rf "$OUT_PATH"

"$PROJECT_PATH/node_modules/.bin/electron-packager" "$PROJECT_PATH" --platform=linux --arch=ia32 --overwrite --icon="$ICON_PATH" --out="$OUT_PATH" --version-string.CompanyName="Hemal Harindaka" --version-string.ProductName="Fox 91.4 Desktop Client" --version-string.ProductVersion="$VERSION" --ignore="$OUT_PATH" --ignore="$PROJECT_PATH/node_modules/electron-packager" --ignore="$PROJECT_PATH/node_modules/electron-prebuilt" --ignore="$PROJECT_PATH/build-tools" 
mv "$OUT_PATH/fox-desktop-linux-ia32" "$OUT_PATH/fox-desktop-linux-ia32-temp"
mkdir "$OUT_PATH/fox-desktop-linux-ia32"
mv "$OUT_PATH/fox-desktop-linux-ia32-temp" "$OUT_PATH/fox-desktop-linux-ia32/bin"
cp -f "$PROJECT_PATH/build-tools/foxdesktop" "$OUT_PATH/fox-desktop-linux-ia32/"
node "$PROJECT_PATH/build-tools/build-helper-zip.js" "$OUT_PATH/fox-desktop-linux-ia32" "$OUT_PATH/fox-desktop-v$VERSION-linux-ia32.zip"

"$PROJECT_PATH/node_modules/.bin/electron-packager" "$PROJECT_PATH" --platform=linux --arch=x64 --overwrite --icon="$ICON_PATH" --out="$OUT_PATH" --version-string.CompanyName="Hemal Harindaka" --version-string.ProductName="Fox 91.4 Desktop Client" --version-string.ProductVersion="$VERSION" --ignore="$OUT_PATH" --ignore="$PROJECT_PATH/node_modules/electron-packager" --ignore="$PROJECT_PATH/node_modules/electron-prebuilt" --ignore="$PROJECT_PATH/build-tools" 
mv "$OUT_PATH/fox-desktop-linux-x64" "$OUT_PATH/fox-desktop-linux-x64-temp"
mkdir "$OUT_PATH/fox-desktop-linux-x64"
mv "$OUT_PATH/fox-desktop-linux-x64-temp" "$OUT_PATH/fox-desktop-linux-x64/bin"
cp -f "$PROJECT_PATH/build-tools/foxdesktop" "$OUT_PATH/fox-desktop-linux-x64/"
node "$PROJECT_PATH/build-tools/build-helper-zip.js" "$OUT_PATH/fox-desktop-linux-x64" "$OUT_PATH/fox-desktop-v$VERSION-linux-x64.zip"

